import { getListItemSecondaryActionClassesUtilityClass } from '@mui/material';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Geist, Geist_Mono } from 'next/font/google';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  )
}
